<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Match justfile syntax for coloring.  Adapted from: https://github.com/casey/just/blob/master/extras/just.sublime-syntax</string>
	<key>fileTypes</key>
	<array>
		<string>justfile</string>
		<string>.justfile</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Justfile</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#annotations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#recipeDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scripts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#settings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#recipeContent</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotations</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unrecognized-annotations.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\[(?:private|no-cd|no-exit-message|linux|macos|unix|windows|([^\[]+))\]</string>
			<key>name</key>
			<string>storage.type.anotation.just</string>
		</dict>
		<key>assignments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.just</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:(export|alias)\s+)?([a-zA-Z_][a-zA-Z0-9_-]*)\s*(:=)</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>#[^!].*</string>
			<key>name</key>
			<string>comment.line.just</string>
		</dict>
		<key>dependent_expression</key>
		<dict>
			<key>begin</key>
			<string>(\()\s*([a-zA-Z_][a-zA-Z0-9_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.paren.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.dependency.just</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.paren.just</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.param.dependent-expression.just</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>variable.other.just</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.paren.just</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.expression.paren.just</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.param.expression.just</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>variable.other.just</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>begin</key>
			<string>(?x:
         \b(arch|os|os_family|env_var|env_var_or_default|invocation_directory|justfile|justfile_directory|
            just_executable|lowercase|quote|replace|trim|trim_end|trim_end_match|trim_end_matches|trim_start|
            trim_start_match|trim_start_matches|uppercase|absolute_path|extension|file_name|file_stem|
            parent_directory|without_extension|join|clean|path_exists|error|sha256|sha256_file|uuid|capitalize|
            uppercamelcase|lowercamelcase|snakecase|kebabcase|shoutysnakecase|titlecase|shoutykebabcase)\b(\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameter-list.begin.just</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameter-list.end.just</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<key>interpolate</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)\{\{(?!\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.string.begin.just</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.string.end.just</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.interpolated.variable.just</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(if|else|while)\b</string>
		</dict>
		<key>recipeContent</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([-@]*)</string>
		</dict>
		<key>recipeDefinition</key>
		<dict>
			<key>begin</key>
			<string>^(@|_)?([a-zA-Z_][a-zA-Z0-9_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.recipe.just</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(#.*)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.just</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.recipe.param-list-terminator.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.recipe.param-list.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>([\+\*\$])?([a-zA-Z_][a-zA-Z0-9_-]*)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.recipe.param.prefix.just</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.recipe.param.just</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.recipe.param-equals.just</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=:)|(?=[a-zA-Z_])</string>
							<key>name</key>
							<string>meta.recipe.param-name.with-default.just</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#strings</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.recipe.param.prefix.just</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.recipe.param.just</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\+\*\$])?([a-zA-Z_][a-zA-Z0-9_-]*)</string>
							<key>name</key>
							<string>meta.recipe.param-name.just</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.recipe.param-equals.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=#)|(?=$)</string>
					<key>name</key>
					<string>meta.recipe.dependent-list.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_][a-zA-Z0-9_-]*</string>
							<key>name</key>
							<string>entity.other.inherited-class.dependency.just</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dependent_expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>recipeDefinition_old</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.just</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.just</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.just</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.just</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.interpolated.just</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.dependency.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(@|_)?([a-zA-Z_][a-zA-Z0-9_-]*)\s*([\+\*\$])?([a-zA-Z0-9_]*)?\s*(=)?\s*([a-zA-Z0-9_-`'"]*):([\sa-zA-Z0-9_-]*).*$</string>
		</dict>
		<key>scripts</key>
		<dict>
			<key>begin</key>
			<string>\s#\!</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.shebang.just</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The #! within a recipe</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>support.type.property-name.just</string>
		</dict>
		<key>settings</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.just</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.just</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unrecognized-setting.just</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.just</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
        ^(set)\s+
        (?:\b(allow-duplicate-recipes|dotenv-load|export|fallback|ignore-comments|positional-arguments|shell|tempdir|windows-shell)\b
          |
          \b([a-zA-Z0-9_-]+)\b  #invalid setting name
        )
        \s*(:=)?
      )</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>```</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>```</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.triple.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.triple.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.triple.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.just</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.just</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.just</string>
	<key>uuid</key>
	<string>F698CC95-3660-42A9-A666-B6C16E93E298</string>
</dict>
</plist>
